package it.unicam.cs.tables;

/**
 * The regions of a table
 * @see Table
 * @author Younes Rabeh
 */
public enum TableRegion {
    LINE,
    WALL,
    UPPER_LEFT_INTERSECTION,
    UPPER_CENTER_INTERSECTION,
    UPPER_RIGHT_INTERSECTION,
    MIDDLE_LEFT_INTERSECTION,
    MIDDLE_CENTER_INTERSECTION,
    MIDDLE_RIGHT_INTERSECTION,
    LOWER_LEFT_INTERSECTION,
    LOWER_CENTER_INTERSECTION,
    LOWER_RIGHT_INTERSECTION;
}
